FROM python:3.6

# Create app directory
WORKDIR /app

# Install app dependencies
COPY flightservice/requirements.txt ./

RUN pip install -r requirements.txt

# Bundle app source
COPY flightservice /app

EXPOSE 8080
CMD ["python","app.py"]